---
title: "DATA 609: Project Proposal"
format: html
editor: source
author: Eddie Xu
---

When writing proposals, I’ve found the following set of considerations, called “Heilmeier's Questions”, to be helpful to consider. Although this is just a very short project, you might find them helpful as well, and useful for formulating future projects and proposals that you might have to complete. These questions were developed by Dr. George Heilmeier, who was the director of DARPA from 1975-1977. Heilmeier said that every proposal to DARPA needed to answer these questions clearly and completely in order to receive funding:

What are you trying to do? Articulate your objectives using absolutely no jargon. What is the problem? Why is it hard?
How is it done today, and what are the limits of current practice?
What is new in your approach, and why do you think it will be successful?
Who cares?
If you’re successful, what difference will it make? What applications are enabled as a result?
What are the risks?
How long will it take?
What are the midterm and final “exams” to check for success? How will progress be measured?

### Problem

Financial companies often need their investment portfolio to meet certain thresholds and regulatory requirement. With many vanilla and complex financial instruments in the market, it is very challenging for companies and auditors to maintain that objective. To ensure the portfolio is to be comply with these constraints, it requires many resources and times for auditing professionals to do. That is a problem since many mistakes can be made during short periods of time and companies can be penalized and fined in millions of dollars. That is the challenge in the current financial industry.

### Approach

The purpose of this project is to use the convex optimization to help detect financial detection and help reduce the workload for professionals. At the moment, not many machine learning techniques or methods are being used in financial auditing and regulatory reporting. 

This approach could be successful since If successful, this approach can help companies detect those deviations or anomalies earlier while maintaining the minimal portfolio return. 